package com.spiritwisestudios.gpstracker.domain.model

import java.util.Date

/**
 * Domain model representing content for a point of interest generated by AI.
 */
data class TourContent(
    val id: String,
    val poiId: String,
    val title: String,
    val content: String,
    val summary: String,
    val createdAt: Date = Date(),
    val updatedAt: Date = Date(),
    val source: ContentSource = ContentSource.AI_GENERATED,
    val metadata: Map<String, String> = emptyMap(),
    val audioDuration: Int? = null,
    val language: String = "en"
) {
    /**
     * Source of the content
     */
    enum class ContentSource {
        AI_GENERATED,
        PRE_POPULATED,
        USER_CONTRIBUTED,
        THIRD_PARTY
    }
    
    /**
     * Returns a shortened version of the content suitable for preview
     */
    fun getPreviewContent(maxLength: Int = 100): String {
        return if (content.length <= maxLength) content
        else content.take(maxLength - 3) + "..."
    }
} 